enum {

    JSON_TRANSACTION_WRONG_TYPE,
    JSON_TRANSACTION_NOT_PRESENT_VALUE,
    JSON_TRANSACTION_INVALID_ACTION
};


enum {
    DTW_ACTION_FILE_NOT_FOUND,
    DTW_ACTION_ITS_NOT_JSON,
    DTW_ACTION_WRITE,
    DTW_ACTION_MOVE,
    DTW_ACTION_MOVE_MERGING,
    DTW_ACTION_COPY,
    DTW_ACTION_COPY_MERGING,
    DTW_ACTION_DELETE
};

