#define DELETE_METHOD "__gc"
#define TO_STRING_METHOD "__tostring"
#define TO_NUMBER_METHOD "__tonumber"
#define TO_BOOLEAN_METHOD "__tobolean"
#define INDEX_METHOD "__index"
#define SUB_RESOURCE_METHOD "sub_resource"
#define GET_BYTE_AT_METHOD "get_byte_at_index"
#define SUB_RESOURCE_NEXT_METHOD "sub_resource_next"
#define SUB_RESOURCE_NOW_METHOD "sub_resource_now"
#define SUB_RESOURCE_NOW_IN_UNIX "sub_resource_now_in_unix"

#define UNLOAD_METHOD "unload"
#define UNLOCK_METHOD "unlock"
#define LOCK_METHOD "lock"

#define SET_VALUE_METHOD "set_value"
#define GET_VALUE_METHOD "get_value"
#define DIGESST_METHOD "digest"
#define DIGESST_FOLDER_BY_CONTENT_METHOD "digest_folder_by_content"
#define DIGESST_FOLDER_BY_LAST_MODIFICATION_METHOD "digest_folder_by_last_modification"
#define DIGESST_FILE_METHOD "digest_file"
#define COMMIT_METHOD "commit"

#define DESTROY_METHOD "destroy"

#define GET_PATH_METHOD "get_path"
#define GET_DIR_METHOD "get_dir"
#define GET_NAME_METHOD "get_name"
#define GET_NAME_WITHOUT_EXTENSION "get_name_without_extension"
#define GET_EXTENSION  "get_extension"
#define SET_EXTENSION_METHOD "set_extension"

#define WRITE_METHOD "write"
#define REMOVE_ANY_METHOD "remove_any"
#define MOVE_ANY_METHOD "move_any"
#define COPY_ANY_METHOD "copy_any"
#define DUMP_TO_JSON_FILE_METHOD "dump_to_json_file"
#define DUMP_TO_JSON_STRING "dump_to_json_string"
#define EACH_METHOD "each"
#define MAP_METHOD "map"
#define COUNT_METHOD "count"
#define FIND_METHOD "find"
#define LIST_METHOD "list"
#define ADD_PRIMARY_KEYS "add_primary_keys"
#define  DANGEROUS_REMOVE_PROP_METHOD "dangerous_remove_prop"
#define  DANGEROUS_RENAME_PROP_METHOD "dangerous_rename_prop"
#define  GET_RESOURCE_MATCHING_PRIMARY_KEY_METHOD "get_resource_matching_primary_key"
#define GET_RESOURCE_BY_NAME_ID "get_resource_by_name_id"
#define SUB_SCHEMA_METHOD "sub_schema"
#define SCHEMA_NEW_INSERTION "new_insertion"
#define SET_VALUE_IN_SUB_RESOURCE_METHOD "resource_set_value_in_sub_resource"