#define DTW_TYPE "dtw_type"
#define SIZE "size"
#define CONTENT_POINTER "dtw_content_pointer"
#define HASH_POINTER "dtw_hash_pointer"
#define RESOURCE_POINTER "dtw_resource_pointer"
#define IS_A_REF "dtw_is_a_ref"
#define TRANSACTION_POINTER "dtw_transaction"