#define ADD_PRIMARY_KEYS "add_primary_keys"
#define  DANGEROUS_REMOVE_PROP_METHOD "dangerous_remove_prop"
#define  DANGEROUS_RENAME_PROP_METHOD "dangerous_rename_prop"
#define  GET_RESOURCE_MATCHING_PRIMARY_KEY_METHOD "get_resource_matching_primary_key"
#define GET_RESOURCE_BY_NAME_ID "get_resource_by_name_id"
#define SCHEMA_NEW_INSERTION "schema_new_insertion"
#define SET_VALUE_IN_SUB_RESOURCE_METHOD "set_value_in_sub_resource"
#define GET_VALUE_FROM_SUB_RESOURCE_METHOD "get_value_from_sub_resource"

#define SCHEMA_COUNT_RESOURCE_METHOD "schema_count"
#define SCHEMA_LIST_RESOURCE_METHOD "schema_list"
#define SCHEMA_FIND_RESOURCE_METHOD "schema_find"
#define SCHEMA_MAP_RESOURCE_METHOD "schema_map"
#define SCHEMA_EACH_METHOD "schema_each"
#define SUB_RESOURCE_NEXT_METHOD "sub_resource_next"
#define SUB_RESOURCE_NOW_METHOD "sub_resource_now"
#define SUB_RESOURCE_NOW_IN_UNIX "sub_resource_now_in_unix"
#define SUB_RESOURCE_METHOD "sub_resource"

#define UNLOAD_METHOD "unload"
#define UNLOCK_METHOD "unlock"
#define LOCK_METHOD "lock"
#define RESOURCE_NEW_SCHEMA "newSchema"
